#theme: jekyll-theme-cayman

title: File Factory

description: small filesystem testing framework

remote_theme: outo/cayman@ad70028dd1aa491c4024da33eed0191c6806e7ea

plugins:
  - jekyll-remote-theme

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: swalak@gmail.com
  facebook: sebastian.walak
  github: outo
  linkedin: sebastian-walak-b7b71687
  googleplus: +SebastianWalak


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-110137727-1


